# Generated by Django 6.1.1 on 2026-10-05 10:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.CharField(blank=True, choices=[('Licence 1', 'L1'), ('Licence 2', 'L2'), ('Licence 3', 'L3'), ('Master 1', 'M1'), ('Master 2', 'M2')], default='Licence 1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='nom_enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignant', to=settings.AUTH_USER_MODEL),
        ),
    ]
