# Generated by Django 6.1.1 on 2026-10-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0002_cours_date_creation_cours_niveau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='date_creation',
        ),
    ]
