# Generated by Django 6.1.1 on 2026-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matiere',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='niveau',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'administrateur'), ('ENSEIGNANT', 'enseignant'), ('ETUDIANT', 'étudiant')], max_length=20),
        ),
    ]
