# Generated by Django 6.1.1 on 2026-10-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0002_customuser_matiere_customuser_niveau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='matiere',
        ),
    ]
